import styles from './country.module.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function CountryLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <div className={styles.container}>
            {children}
        </div>
    )
}
